### ISSUE TITLE
FBI's Absolute Fucking Pile of Shit that will be reported at the same time

### ISSUE THREAD

**Issue by bruhmogus** [Guloveos/Arcadis-station-14#5]
fuck you it's a list

- [x] Fix flesh runner name and desc capitalization
- [x] Fix spawner meat hub name and desc capitalization
- [x] Add period to the end of FBI coat
- [x] Fix moose mask spelling and punctuation
- [x] Fix cool coder socks punctuation
- [x] Add NTPD air tank

**Comment by TheDoctor1977** [comment]
NTPD probably don't need their own air tanks, but I'll leave it up to Gul

**Comment by bruhmogus** [comment]
> NTPD probably don't need their own air tanks, but I'll leave it up to Gul

they dont spawn with airtanks is the problem

**Comment by TheDoctor1977** [comment]
everything is checked, so i suppose this is done
